create table proveedores (
   id_proveedor number
      generated by default as identity
   primary key,
   nombre       varchar2(100) not null,
   direccion    varchar2(150),
   telefono     varchar2(20),
   correo       varchar2(100)
);
create table insumos (
   id_insumo     number
      generated by default as identity
   primary key,
   nombre        varchar2(100) not null,
   descripcion   varchar2(200),
   unidad_medida varchar2(50),
   fecha_ingreso date,
   id_proveedor  number,
   calidad       varchar2(50),
   foreign key ( id_proveedor )
      references proveedores ( id_proveedor )
);

create table ordenes_compra (
   id_orden     number
      generated by default as identity
   primary key,
   fecha        date not null,
   id_proveedor number not null,
   estado       varchar2(50),
   foreign key ( id_proveedor )
      references proveedores ( id_proveedor )
);
create table detalle_orden_compra (
   id_detalle      number
      generated by default as identity
   primary key,
   id_orden        number not null,
   id_insumo       number not null,
   cantidad        number,
   precio_unitario number(10,2),
   foreign key ( id_orden )
      references ordenes_compra ( id_orden ),
   foreign key ( id_insumo )
      references insumos ( id_insumo )
);
create table inspecciones_calidad (
   id_inspeccion    number
      generated by default as identity
   primary key,
   id_insumo        number not null,
   fecha_inspeccion date,
   resultado        varchar2(50),
   observaciones    varchar2(200),
   foreign key ( id_insumo )
      references insumos ( id_insumo )
);


